# Firebot workflow

name: Line_Endings

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-line-endings:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - name: Check for CRLF line endings
        run: |
          { grep -IUlr --exclude={"*.pdf","*.png"} --exclude-dir=".git" $'\r' > tmp.txt || true; }
          nlines=$(cat tmp.txt | wc -l)
          if [ $nlines -gt 0 ]; then
            echo "text files with dos line endings:"
            cat tmp.txt
            exit 1
          fi




