name: github-linux


on:
  push:
    paths:
    - .github/**
    - Build/**
    - Source/**
  pull_request:
    paths:
    - .github/**
    - Build/**
    - Source/**


concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


permissions:
  contents: read

jobs:
  linux-intel-intelmpi:
    # build on ubuntu using ifort with intelmpi and mkl based on
    # https://github.com/oneapi-src/oneapi-ci

    name: linux intel intelmpi
    runs-on: [ubuntu-latest]

    steps:
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: |
          ifx
          impi
          mkl

    - uses: actions/checkout@v4
    - name: build fds debug
      run: |
        source /opt/intel/oneapi/setvars.sh
        cd ./Build/impi_intel_linux_db
        sh ./make_fds.sh
        ./fds_impi_intel_linux_db
    - name: build fds release
      run: |
        source /opt/intel/oneapi/setvars.sh
        cd ./Build/impi_intel_linux
        export INTEL_IFORT=ifx
        sh ./make_fds.sh
        ./fds_impi_intel_linux

    # Setup python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r .github/requirements.txt

    # Run Hello World test
    - name: Python test
      run: |
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE/Utilities/Python
        python hello_world.py
        python FDS_verification_script.py

  linux-gnu-openmpi:
    # build on ubuntu using gfortran with openmpi and mkl based on
    # https://github.com/oneapi-src/oneapi-ci

    name: linux gnu openmpi
    runs-on: [ubuntu-latest]

    steps:
    - name: install openmpi
      run: |
        sudo apt-get update
        sudo apt-get install libopenmpi-dev openmpi-bin
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: |
          mkl

    - uses: actions/checkout@v4
    - name: build fds debug
      run: |
        source /opt/intel/oneapi/setvars.sh
        cd ./Build/ompi_gnu_linux_db
        sh ./make_fds.sh
        ./fds_ompi_gnu_linux_db
    - name: build fds release
      run: |
        source /opt/intel/oneapi/setvars.sh
        cd ./Build/ompi_gnu_linux
        sh ./make_fds.sh
        ./fds_ompi_gnu_linux
