name: github-osx


on:
  push:
    paths:
    - .github/**
    - Build/**
    - Source/**
  pull_request:
    paths:
    - .github/**
    - Build/**
    - Source/**


concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


permissions:
  contents: read


jobs:
  osx-gnu-openmpi:
    # debug build on osx using gfortran with openmpi
  
    name: osx gnu openmpi
    runs-on: [macos-14]
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v5
    - name: install openmpi
      run: |
        brew install gcc@15 open-mpi
        echo "OMPI_FC=gfortran-15" >> $GITHUB_ENV

    - name: build fds debug
      run: |
        cd ./Build/ompi_gnu_osx_db
        sh ./make_fds.sh
        ./fds_ompi_gnu_osx_db
    - name: build fds release
      run: |
        cd ./Build/ompi_gnu_osx
        sh ./make_fds.sh
        ./fds_ompi_gnu_osx
